name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mdbook
        run: cargo install mdbook
      - name: Build book
        run: mdbook build

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"
      - name: Install vmdfmt
        run: go install github.com/bobertlo/vmd/cmd/vmdfmt@latest
      - name: Check formatting
        run: |
          export PATH="$PATH:/tmp/go/bin:$(pwd)/node_modules/.bin"
          ./ci/check_format.sh

  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -v -r -c 30 *
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
